### PR TITLE
Added tests directory as a default when linting.

### PR DESCRIPTION
**Pull request by Limpan**
Maybe this is a good idea?

### CODE REVIEW

**Comment by Greenheart** [comment]
To run linting for tests as well? It's probably a good idea! :+1:

**Comment by Greenheart** [comment]
@Limpan what do you think about using the yellow label for PR's and the orange for issues? :santa:

**Comment by Limpan** [comment]
I thought you meant to use the yellow to tell that code review was needed and the orange for general QA discussions and specific code. I'll use them however you want them to be used.

**Comment by Greenheart** [comment]
No problem :blush: 

@teknik-eksjo/te13 How about using the yellow label ("QA needed before merge") on PR:s that haven't been QA:ed yet. When it's ready to merge according to the reviewer, remove it or merge directly.

Then we could use the orange label ("quality assurance") on issues related to improving maintainability, increasing performance etc.

**Comment by Greenheart** [comment]
@Limpan I'll review this soon.

Edit: I think this is ready. Tested locally without any problems

**Pull request merged**
