### PR TITLE
Updates to config.py for Travis CI.

### PR DESCRIPTION
**Pull request by Limpan**
The docker container for PostgreSQL has been changed so that it creates two extra databases that will be used for development and testing.

Please update your .env file accordingly.

### CODE REVIEW

**Comment by Greenheart** [comment]
@Limpan I can't get the server to start since i pulled this change in. Could you provide the steps we need to take to make it work apart from just changing the .env? :smile: 

#### .env

```
CHRONOS_ADMIN=(...)
MAIL_USERNAME=(...)
MAIL_PASSWORD=(...)
DEV_DATABASE_URI=postgresql+psycopg2://postgres:secretpassword@localhost/development
TEST_DATABASE_URI=postgresql+psycopg2://postgres:secretpassword@localhost/testing
DATABASE_URI=postgresql+psycopg2://postgres:secretpassword@localhost/postgres
```

---

## Actions taken
1. updated .env
2. rebuilt the container with `docker-compose build --no-cache`

**Comment by Limpan** [comment]
1. Stop the old postgres container.
   `docked ps`
   `docker stop chronos_postgres_1` or whatever name ps said
2. Build the new container and start it.
   `docker-compose build` where you might want to add `--no-cache` if it's not working later.
   `docker-compose up -d`

That should be it. To connect directly to the database manager do
`docker exec -it chronos_postgres_1 psql -U postgres`

**Comment by Greenheart** [comment]
Thank you for the reply! :)

I followed your instructions but it still doesn't work.
The last command gives me a prompt but not even the "help"-command is working

**Comment by Limpan** [comment]
What does `docker-compose logs postgres` say?

Have you tried to restart docker? `service docker restart` I think.

Maybe this could help? http://stackoverflow.com/questions/32723111/how-to-remove-old-and-unused-docker-images

**Comment by Greenheart** [comment]
> docker-compose logs postgres

`ERROR: No such service: postgres`

---

The Accepted answer from SO deleted 4 contianers

**Comment by Limpan** [comment]
What about `docker-compose logs postgresql`?

**Comment by Greenheart** [comment]
There we have it, we referenced the wrong name ^^

```

postgresql_1  | LOG:  database system was shut down at 2016-04-28 20:13:59 UTC
postgresql_1  | LOG:  MultiXact member wraparound protections are now enabled
postgresql_1  | LOG:  autovacuum launcher started
postgresql_1  | LOG:  database system is ready to accept connections
postgresql_1  | FATAL:  database "development" does not exist
postgresql_1  | FATAL:  database "development" does not exist
postgresql_1  | FATAL:  database "development" does not exist
```

---

Maybe i need to change `postgres` to `postgresql_1` somewhere?

**Comment by Greenheart** [comment]
@Limpan YES!

The error message craching the app changed!
``sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL: password authentication failed for user "postgresql"

So in the `.env`-file, DB-lines should look like following. **(But with other passwords)**
```
DEV_DATABASE_URI=postgresql+psycopg2://postgresql:secretpassword@127.0.0.1/development
TEST_DATABASE_URI=postgresql+psycopg2://postgresql:secretpassword@127.0.0.1/testing
DATABASE_URI=postgresql+psycopg2://postgresql:secretpassword@127.0.0.1/postgres
```

**Comment by Greenheart** [comment]
Nvm, I changed my .env back to what it looked like before.

I hadn't tried `./manage.py deploy` -- but it just gave me the same error `sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL: database "development"`

**Comment by Limpan** [comment]
If you do
`docker-compose down`
`docker ps`
and make sure no containers are running and then
`docker-compose build --no-cache`
`docker-compose up`
and look for `CREATE DATABASE` in the output. The new build is supposed to create two extra databases `development` and `testing`. It does not seem to have happened.

**Comment by Greenheart** [comment]
```
(venv) sam@ubbe:~/Documents/github/chronos/web$ sudo docker-compose up
Creating chronos_postgresql_1
Attaching to chronos_postgresql_1
postgresql_1  | The files belonging to this database system will be owned by user "postgres".
postgresql_1  | This user must also own the server process.
postgresql_1  | 
postgresql_1  | The database cluster will be initialized with locale "en_US.utf8".
postgresql_1  | The default database encoding has accordingly been set to "UTF8".
postgresql_1  | The default text search configuration will be set to "english".
postgresql_1  | 
postgresql_1  | Data page checksums are disabled.
postgresql_1  | 
postgresql_1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
postgresql_1  | creating subdirectories ... ok
postgresql_1  | selecting default max_connections ... 100
postgresql_1  | selecting default shared_buffers ... 128MB
postgresql_1  | selecting dynamic shared memory implementation ... posix
postgresql_1  | creating configuration files ... ok
postgresql_1  | creating template1 database in /var/lib/postgresql/data/base/1 ... ok
postgresql_1  | initializing pg_authid ... ok
postgresql_1  | initializing dependencies ... ok
postgresql_1  | creating system views ... ok
postgresql_1  | loading system objects' descriptions ... ok
postgresql_1  | creating collations ... ok
postgresql_1  | creating conversions ... ok
postgresql_1  | creating dictionaries ... ok
postgresql_1  | setting privileges on built-in objects ... ok
postgresql_1  | creating information schema ... ok
postgresql_1  | loading PL/pgSQL server-side language ... ok
postgresql_1  | vacuuming database template1 ... ok
postgresql_1  | copying template1 to template0 ... ok
postgresql_1  | copying template1 to postgres ... ok
postgresql_1  | syncing data to disk ... ok
postgresql_1  | 
postgresql_1  | Success. You can now start the database server using:
postgresql_1  | 
postgresql_1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
postgresql_1  | 
postgresql_1  | 
postgresql_1  | WARNING: enabling "trust" authentication for local connections
postgresql_1  | You can change this by editing pg_hba.conf or using the option -A, or
postgresql_1  | --auth-local and --auth-host, the next time you run initdb.
postgresql_1  | waiting for server to start....LOG:  database system was shut down at 2016-04-28 21:19:04 UTC
postgresql_1  | LOG:  MultiXact member wraparound protections are now enabled
postgresql_1  | LOG:  autovacuum launcher started
postgresql_1  | LOG:  database system is ready to accept connections
postgresql_1  |  done
postgresql_1  | server started
postgresql_1  | ALTER ROLE
postgresql_1  | 
postgresql_1  | 
postgresql_1  | /docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init.sql
postgresql_1  | CREATE DATABASE
postgresql_1  | CREATE DATABASE
postgresql_1  | 
postgresql_1  | 
postgresql_1  | LOG:  received fast shutdown request
postgresql_1  | LOG:  aborting any active transactions
postgresql_1  | waiting for server to shut down....LOG:  autovacuum launcher shutting down
postgresql_1  | LOG:  shutting down
postgresql_1  | LOG:  database system is shut down
postgresql_1  |  done
postgresql_1  | server stopped
postgresql_1  | 
postgresql_1  | PostgreSQL init process complete; ready for start up.
postgresql_1  | 
postgresql_1  | LOG:  database system was shut down at 2016-04-28 21:19:07 UTC
postgresql_1  | LOG:  MultiXact member wraparound protections are now enabled
postgresql_1  | LOG:  database system is ready to accept connections
postgresql_1  | LOG:  autovacuum launcher started
```

**Comment by Limpan** [comment]
Looks good.
What about `docker exec -it chronos_postresql_1 psql -U postgres` and `\l` as command? You should get a list of databases that contain our three plus one or two more.

**Comment by Greenheart** [comment]
```
postgres=# \l
                                  List of databases
    Name     |  Owner   | Encoding |  Collate   |   Ctype    |   Access privileges   
-------------+----------+----------+------------+------------+-----------------------
 development | postgres | UTF8     | en_US.utf8 | en_US.utf8 | 
 postgres    | postgres | UTF8     | en_US.utf8 | en_US.utf8 | 
 template0   | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
             |          |          |            |            | postgres=CTc/postgres
 template1   | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
             |          |          |            |            | postgres=CTc/postgres
 testing     | postgres | UTF8     | en_US.utf8 | en_US.utf8 | 
(5 rows)
```

---

No access privileges? Could that be an issue?

**Comment by Limpan** [comment]
Can you run `./manage.py deploy` now?

**Comment by Greenheart** [comment]
Yes! Hmmmm, what happened here? :stuck_out_tongue:

**Comment by Limpan** [comment]
I think the old container was with us for a few more moments than we wanted.

**Comment by Greenheart** [comment]
@Limpan Yeah that seems to be the case when I look back at our conversation and the errors i got earlier.

**A BIG thank you** for helping out and especially by this time of the day! ^^

**Pull request merged**
