### PR TITLE
Added routes, forms and views for managing work-periods

### PR DESCRIPTION
**Pull request by Greenheart**
**Note:** This should be squashed when merged in order to remove commit `0d64fad` but keep it's changes

---

This is an initial version of this feature that is tested locally and working (although with bad UX atm)

Additionally...
- Updated the model for `WorkPeriod`s
- Updated `add.html` and `edit.html` to make them reusable for both
  `/teachers` and `/work-periods`

### CODE REVIEW

**Comment by Greenheart** [comment]
This is the error

`sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  database "travis_ci_test" does not exist`

@Limpan How could I fix this?

**Comment by Limpan** [comment]
Solution is in issue #92. If you rebase your branch so that you get the commit from #92 it should work.

**Comment by Greenheart** [comment]
@Limpan Thanks, I'll try it! :+1: :+1: 

**Edit:** Seems like the tests are hanging exactly the same way as they did for you earlier

**Comment by Limpan** [comment]
I'll investigate more later...

**Comment by Limpan** [comment]
Turns out I had reversed the logic for `--no-html` and `--no-report` for the test command. Probably happened when I ported from click to flask_script.

The coverage report is created in `web/tmp/coverage` and you could create a file `web/tmp/users.txt` with your script. This pull request makes sure that the `tmp` directory is ignored.

**Comment by Greenheart** [comment]
@Limpan Thank you, this will make it easier to create good tests!

@teknik-eksjo/te13 The next question is what I should do to get this PR merged. Any feedback or improvements you want me to make? :)

**Comment by hugolundin** [comment]
The commit log does not look as good as it should do 😁

**Comment by Greenheart** [comment]
It's still not passing the tests (because of problems with .env in
travis?) :P

Either I could rebase it or maybe it's sufficient to just squash wen
merging?

**Comment by Limpan** [comment]
It's a pain for someone else to write a good commit message.

You know what parts of the code is in these commits, you know if they're multiple features (and should be multiple commits) or just one feature with a few too many commits.

The result will be better and less time will be spent if you rebase the commits into one or many commits with good, descriptive, commit messages.

**Comment by Greenheart** [comment]
@teknik-eksjo/te13 Rebased. There's definitely something wrong with the Python 3.5 build. Maybe some dependency or environment-variable that need to be configured?

**Comment by hugolundin** [comment]
Can @Limpan take a look at this before we merge?

**Pull request merged**
