### PR TITLE
Added fixtures for database session.

### PR DESCRIPTION
**Pull request by Limpan**
When writing tests that need the session object use `session` as argument. The fixture will then make sure to clean the database between tests.

### CODE REVIEW

**Comment by Greenheart** [comment]
Great improvement!

**Comment by Limpan** [comment]
Seems like the Travis build hangs after the last test on Python 3.5. On my local 3.5 install all tests run fine. Is it some kind of weird bug, maybe?

**Comment by Greenheart** [comment]
It's the same problem as I get. Probably environment variables for travis!

**Comment by Greenheart** [comment]
@teknik-eksjo/te13 Is this ready to be merged or what do you say?

**Comment by Limpan** [comment]
I'd say it's ready to merge!

**Pull request merged**
