### PR TITLE
Added leave prevention for edit/add work-period

### PR DESCRIPTION
**Pull request by hugolundin**
Resolves issue #114

### CODE REVIEW

**Comment by Greenheart** [comment]
This doesn't prevent users from leaving unsaved changes when **adding new work-periods**.

Maybe the script doesn't work for that form or isn't included properly?

**Comment by hugolundin** [comment]
It works if you fill in the whole date on the add page, which is really strange.

**Comment by Limpan** [comment]
I can see the reasoning behind the behaviour. Either you have a date or you don't. Why send change events or any event at all when you half-change things?

**Comment by Greenheart** [comment]
@hugolundin Haha I noticed that too. 

@Limpan I think we should ignore this issue for now only fix it if we notice any problems when the actual datepicker is in place.

**Pull request merged**
